networks:
  inception:
    name: inception

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    restart: always
  mariadb:
    image: mariadb:latest
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:latest
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/lib/mysql
      - wordpress_website:/var/www/html
    networks:
      - inception
    restart: always
  ftp:
    image: ftp:latest
    build: ./requirements/bonus/ftp
    container_name: ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    volumes:
      - wordpress_website:/home/ftpuser/ftp/wordpress
    networks:
      - inception
    restart: always
  adminer:
    image: adminer:latest
    build: ./requirements/bonus/adminer
    container_name: adminer
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  redis:
    image: redis:latest
    build: ./requirements/bonus/redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  website:
    image: website:latest
    build: ./requirements/bonus/website
    container_name: website
    env_file:
      - .env
    ports:
      - "7000:7000"
    networks:
      - inception
    restart: always
  cadvisor:
    image: cadvisor
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    env_file:
      - .env
    volumes:
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

version: '3.9'

volumes:
  wordpress_website:
    name: wordpress_website
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_website
  wordpress_database:
    name: wordpress_database
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_database
