
networks:
  network: {}

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - network
    depends_on:
      - mariadb
      - wordpress
    restart: always
  mariadb:
    image: mariadb:latest
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/lib/mysql
    networks:
      - network
    restart: always
  wordpress:
    image: wordpress:latest
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/lib/mysql
      - wordpress_website:/var/www/html
    networks:
      - network
    restart: always
  ftp:
    image: ftp:latest
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    ports:
      - "40000-40010:40000-40010"
      - 21:21
    networks:
      - network
    restart: always
      #adminer:
      #image: adminer:latest
      #build: ./requirements/bonus/adminer
      #env_file:
      #- .env
        #volumes:
      #- wordpress_website:/var/www/html
        #networks:
      #- network
        #restart: always

version: '3.9'

volumes:
  wordpress_website:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_website
  wordpress_database:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_database
