services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - wordpress_website:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      - network
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress_database:/var/lib/mysql
      - wordpress_website:/var/www/html
    networks:
      - network
  mariadb:
    image: mariadb:latest
    volumes:
      - wordpress_database:/var/lib/mysql
    networks:
      - network

version: '3.9'

volumes:
  wordpress_website:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_website
  wordpress_database:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mhar/data/wordpress_database

networks:
  network:
